# -*- coding: utf-8 -*-
"""Data Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K5x030FFLF65hRZpgl1d5kyDH2bxuMzL
"""

import pandas as pd

df = pd.read_csv('employees.csv')

print(df)

from google.colab import drive
drive.mount('/content/drive')

df.fillna(130, inplace = True)
print(df.to_string())

df.loc[7, 'Duration'] = 45
print(df.to_string())

df['Date'] = pd.to_datetime(df['Date'])
print(df.to_string())